### ISSUE TITLE
Create "Contributors" page to give credit. 

### ISSUE THREAD

**Issue by joeyda3rd** [Flutter-Buddies/App#12]
We can even create a github team for the contributors to the app functionality and load their info through github api.

**Comment by slovnicki** [comment]
You mean like contributors for the general stuff in App, not creators of `user_widgets` who are obviously listed in app?

Like, for example, we can put
- joey, the creator of App and user_widgets structure
- doug, prettyfication master
- user123, solved an important bug #42
- ...
?

**Comment by joeyda3rd** [comment]
Correct. Users that have contributed to the functionality of the app. We don't NEED to list their contributions, but we can if you want to. The members list (user_widgets) is for anyone that wants to contribute a widget.

**Comment by joeyda3rd** [comment]
Use github API to load "participants" from app repo

**Comment by joeyda3rd** [comment]
Upon reviewing the API, the only way that I can see to possibly do this is to create a "team" and add any contributors to the team. The contributors URL is adding anyone that pushes to the repo. Maybe this is feature is not necessary? We could instead add a flag to their widgetinfo class.

**Comment by slovnicki** [comment]
I like the idea of just flag on their widget. That's even more cool. I definitely vote for that

**Comment by slovnicki** [comment]
I'm closing this and opening https://github.com/Flutter-Buddies/App/issues/30

**Comment by slovnicki** [comment]
I'm closing this and opening https://github.com/Flutter-Buddies/App/issues/30
