### ISSUE TITLE
some explanation of difference between WidgetInfo.name and WidgetInfo.developer

### ISSUE THREAD

**Issue by slovnicki** [Flutter-Buddies/App#20]

**Comment by Goober0329** [comment]
I _think_ that WidgetInfo.name is the name of your developer widget.

**Comment by slovnicki** [comment]
@Goober0329 yeah, it seems like that, but... What does that mean and how it is used? :shrug: 
I mean, I see how it's used, but think that it should be explained more clearly.

**Comment by joeyda3rd** [comment]
I added a comment, this "name" was not used in the design, but still can be used if design is changed.
