### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by slovnicki** [Flutter-Buddies/App#3]
Explain in detailed steps how to contribute your widget and reference this document in README.

**Comment by joeyda3rd** [comment]
Good thought. I'll do that now.

**Comment by slovnicki** [comment]
I was thinking of doing it, but sure. You can then assign yourself instead of me

**Comment by slovnicki** [comment]
Also include the how-to for pull requests and stuff.
You can get your inspiration from https://github.com/Flutter-Buddies/tic_tac_no/blob/master/CONTRIBUTING.md, without all the branches stuff I guess.
