### ISSUE TITLE
Prettify the user widget list

### ISSUE THREAD

**Issue by joeyda3rd** [Flutter-Buddies/App#5]

**Comment by Zambrella** [comment]
I'm happy to do this. Please can you assign to me

**Comment by Zambrella** [comment]
<img width="474" alt="Screenshot 2020-12-24 at 10 48 48" src="https://user-images.githubusercontent.com/53582591/103083968-aac01e00-45d5-11eb-99c5-c9140e1916d5.png">
Thinking something like this.

**Comment by Zambrella** [comment]
<img width="463" alt="Screenshot 2020-12-24 at 11 26 01" src="https://user-images.githubusercontent.com/53582591/103085859-d5f93c00-45da-11eb-9ce9-998a39953f45.png">
Also drafted up the home page

**Comment by slovnicki** [comment]
Looking good. You have been assigned 🙂

**Comment by Zambrella** [comment]
<img width="570" alt="Screenshot 2020-12-24 at 17 17 07" src="https://user-images.githubusercontent.com/53582591/103100720-da8a1880-460b-11eb-9d5c-44e782df449d.png">
Developer page done. Any feedback let me know.

**Comment by Zambrella** [comment]
<img width="556" alt="Screenshot 2020-12-24 at 18 13 28" src="https://user-images.githubusercontent.com/53582591/103102410-b9c5c100-4613-11eb-8995-325029fb5d1d.png">
Don't like this one very much. Will give it a re-think later after a break.

**Comment by Zambrella** [comment]
<img width="427" alt="Screenshot 2020-12-26 at 18 12 17" src="https://user-images.githubusercontent.com/53582591/103159074-026cae00-47bd-11eb-91f7-1b50a06f35e5.png">

**Comment by Zambrella** [comment]
Can we mark this as complete? I know there are things to improve but I think the general prettification is done?
